USE `plenta_db`;

INSERT INTO `user` (`name`)
VALUES ("Coryhoea"),
       ("Daniel"),
       ("Kate"),
       ("Lilia"),
       ("Maria"),
       ("Paul"),
       ("Helena"),
       ("Andrew"),
       ("Kate"),
       ("Max"),
       ("Alex"),
       ("Maria"),
       ("Gleb");

INSERT INTO `photo_post` (`description`, `creation_date`, `photo_link`, `user_id`)
VALUES ("Lorem ipsum dolor sit amet, hello consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam",
        "2019-05-09T23:58:00",
        "../img/articles/Photo_1.png",
        1),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet lacinia lorem, sit amet vehicula erat. Nulla metus tellus, pellentesque vitae malesuada vitae, pulvinar quis libero. Donec metus.",
        "2019-02-24T07:58:00",
        "../img/articles/Photo_2.png",
        1),
       ("Lorem ipsum dolor sit amet, consectetur hello adipiscing elit. Nunc sit amet lacinia lorem, sit amet vehicula erat. Nulla metus tellus, pellentesque vitae malesuada vitae, pulvinar quis libero.",
        "2018-05-09T07:58:00",
        "../img/articles/Photo_19.png",
        1),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet lacinia lorem, sit amet vehicula erat. Nulla metus tellus, pellentesque vitae malesuada vitae, pulvinar quis libero. Donec metus.",
        "2019-05-01T19:58:00",
        "../img/articles/Photo_21.png",
        1),
       ("Lorem ipsum dolor sit amet, consectetur hellohello adipiscing elit. Nulla lacinia posuere nisi, nec pretium orci pulvinar vitae. Aliquam eget magna quam posuere.",
        "2019-02-24T08:56:00",
        "../img/articles/Photo_3.png",
        3),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lacinia posuere nisi, nec pretium orci pulvinar vitae. Aliquam eget magna quam posuere.",
        "2017-05-09T09:58:00",
        "../img/articles/Photo_4.png",
        1),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam aliquam pulvinar placerat. Sed sed.",
        "2019-02-24T09:00:00",
        "../img/articles/Photo_5.png",
        2),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam augue sem, consequat nec aliquam sed.",
        "2019-05-09T10:58:00",
        "../img/articles/Photo_6.png",
        4),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam faucibus vitae leo quis amet.",
        "2019-05-09T11:22:00",
        "../img/articles/Photo_7.png",
        2),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc erat nibh, congue eget justo ut, venenatis tempus ligula.",
        NOW(),
        "../img/articles/Photo_8.png",
        2),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis, neque a rhoncus rutrum, nulla arcu consectetur risus, ut pretium mi sem sit amet tellus turpis duis.",
        NOW(),
        "../img/articles/Photo_9.png",
        7),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis, neque a rhoncus rutrum, nulla arcu consectetur risus, ut pretium mi sem sit amet tellus turpis duis.",
        NOW(),
        "../img/articles/Photo_10.png",
        7),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis, neque a rhoncus rutrum, nulla arcu.",
        NOW(),
        "../img/articles/Photo_11.png",
        7),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis, neque a rhoncus rutrum, nulla arcu consectetur risus, ut pretium mi sem sit amet tellus turpis duis.",
        NOW(),
        "../img/articles/Photo_12.png",
        7),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis, neque a rhoncus rutrum, nulla arcu consectetur risus, ut pretium mi sem sit  mi sem sit amet amet tellus turpis duis.",
        NOW(),
        "../img/articles/Photo_13.png",
        2),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis, neque a rhoncus rutrum, nulla arcu consectetur risus, ut pretium mi sem sit amet  mi sem sit amet tellus turpis duis.",
        "2019-02-24T09:58:00",
        "../img/articles/Photo_14.png",
        1),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis, neque a rhoncus rutrum, nulla arcu consectetur risus, ut pretium mi sem sit amet tellus turpis duis.",
        NOW(),
        "../img/articles/Photo_15.png",
        2),
       ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis, neque a rhoncus rutrum, nulla arcu consectetur risus, ut pretium mi sem sit amet tellus turpis duis.",
        NOW(),
        "../img/articles/Photo_10.png",
        2);